name: Trigger Netlify Build
on:
  schedule:
    - cron: '00 8 * * *' # 8am every day
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e5e56fe2c31dc619a3508df